service: example-service

frameworkVersion: ">=3.19.0 <4.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1

plugins:
  - serverless-go-plugin

functions:
  example:
    handler: ./src/functions/ # or just "./functions/example"
